.global message

message:
    .ascii "dit zouden ze moet@93afschaffen\n"
    .ascii "\n"
    .ascii "Wilhelmus van Nassouwe \n"
    .ascii " Ben ick@F5Duytsch@A3Bloedt,@O3D@O3Vaderland ghetrouwe@I3Blijf ick tot inden doet;@K3E@;3Prince van Orangi@O3\n"
    .ascii " B@U3ick vry onverveert.@I3D@O3Conin@M4an Hispangi@F3\n"
    .ascii " Heb i@H3altijt gheeert.\n"
    .ascii "\n"
    .ascii "In Godes vre@53te leven \n"
    .ascii " Heb ick altijt betracht,@J3Daerom@B3n@Q5verdrev@=3\n"
    .ascii " Om Land, @O3Luyd ghebracht:@M3Maer Godt sal my regeren@J3Als e@93goet Instrument,@J3Dat ick sal wederkeeren@I3In mijn@;3Regiment.\n"
    .ascii "\n"
    .ascii "Lijdt U,@J5 Ondersaten, \n"
    .ascii " Die oprecht z@N4van aert@L4Godt sal u niet verlaten@J3Al zijt ghy nu beswaert:@J3Die vroom@E3ghe@E3 te leven,@N3Bidt Go@43nacht ende d@:3.@L3Dat Hy my cr@M5wil gheven@M7ick u help@B3m@S3.\n"
    .ascii "\n"
    .ascii "Lijf ende goed al te sam@Q3\n"
    .ascii " Heb ick u niet verschoont,@L3Mijn Broed@F3, @G3ch van Namen@Q4Hebbent u @K3k vertoont:@J3Graef Adolff is ghebleven,@L3In Vrieslandt in den Slach@M4Sijn siel@I3t eewich lev@S3\n"
    .ascii " Verw@W3t d@>3jonghst@H3d@C3.\n"
    .ascii "\n"
    .ascii "Edel @W3Hooch ghebor@W3\n"
    .ascii " Van Keyserlick@Q3stam:@H3E@N3Vorst des Rijcks vercoren,@P3Als e@T3vroom Christen-ma@M5Voor Godes W@:3t ghepreese@N5Heb ick vrij onversaecht@K4Als een helt zonder@W3ees@C3\n"
    .ascii " Mijn edel bloet gewaecht.\n"
    .ascii "\n"
    .ascii "@J5schilt ende betrouwen \n"
    .ascii " Zijt ghy, O Godt, mijn Heer.@N3Op U soo wil ick bouwen,@J3Verlaet my nimmermeer;@H3Dat ick doch vroom mag blijven@P3U dienaer t'all@73stond@I3Die tyranny verdrijven,@I7my mijn hert doorwondt.\n"
    .ascii "\n"
    .ascii "Val @23d@S6beswaren, \n"
    .ascii " End mijn vervolghers z@@3@L4M@H4Godt wilt doch bewaren@M3D@53trouw@=3dienaer@73jn:@K4at sy my niet verasschen@K3In haer@;3boos@B3moet,@H3H@E3@J3nd@V3niet @R3wassch@T3\n"
    .ascii " In mijn on@A3uldich bloet.\n"
    .ascii "\n"
    .ascii "Als David moeste vluchten \n"
    .ascii " Voor Saul d@?3tyran:@F3Soo heb ick moet@K3such@74\n"
    .ascii " Met menich edelman:@E4aer Godt heef@54m verheven,@O3Verlost uit alder noot@I4Een Coninckrijck ghe@23v@F3\n"
    .ascii " In Israel, seer groot.\n"
    .ascii "\n"
    .ascii "Na tsu@@3sal ick ontfanghen \n"
    .ascii " Van Godt, mijn Heer, dat soe@D3\n"
    .ascii " Daer na@?3 d@B3 verlanghen@L3Mijn vorstelick @F3m@T3,@J3Dat is, d@74@J3mag @V3rven@M3Met eeren, in@S5velt,@I3E@O3eeuwich rijk@H3rwerv@F3\n"
    .ascii " Als@L3n ghetrouwe helt.\n"
    .ascii "\n"
    .ascii "Niets doet my meer erbarmen \n"
    .ascii " In mijn@;3wedersp@W3,@G3Dan dat @U4siet verar@=4@K3es Conincks land@S3goet,@K4at ud de Spaengiaerts crencken@R4O edel Neerlandt soet@H4Als ick daeraen ghedencke@L4Mijn @?3l hert@S3t bloet.\n"
    .ascii "\n"
    .ascii "Als een Prins opgheset@@3\n"
    .ascii " Met mijnes heyr@63cracht,@K3Van d@U3tyr@93vermet@>3\n"
    .ascii " Heb ick@L5slach@L4w@73t,@M3Die, by Maestri@E3 begraven@N4Bevreesde mijn ghewelt;@I3M@?4ruyters sach men drav@63\n"
    .ascii " Seer moedi@I3door dat velt.\n"
    .ascii "\n"
    .ascii "Soo het den wil@73s Heer@>3\n"
    .ascii " Op die tijt had gheweest,@K3H@?3ick geern willen k@<3@63\n"
    .ascii " Van u dit swaer tempeest:@K3M@@4de He@H3van hi@Q3boven@M3Die alle dinck reg@V3t,@I7m@S3altijt moet loven@L4En heeft@C3ni@H3begeert.\n"
    .ascii "\n"
    .ascii "S@73 christlick was ghedreven \n"
    .ascii " Mijn prince@O5@K3moet,@J3Stantvastich is@J4bleven@K3Mijn hert in te@J3nspoet,@K3D@Q3Heer@O3b ick @M3bed@E3\n"
    .ascii " Van mijnes@M3rt@C3gront,@J3Dat Hy@M5 saeck wil reden@N4M@G4onschult doe@=3ircont.\n"
    .ascii "\n"
    .ascii "Oorlof m@S4arme @V3apen, \n"
    .ascii " Die zijt in grooten n@63.@K3U Herder sal niet slapen,@K3Al zijt ghy nu verstroit:@K3Tot Godt wilt u begheven,@K3Sijn heylsaem woort neemt a@P6Als vrome Christen lev@K6Tsal hier haest zijn ghedaen.\n"
    .ascii "\n"
    .ascii "Voor Godt wil ick belijden \n"
    .ascii " End sijner groot@73macht,@K3Dat ick tot gheenen tijd@63@L3@<3Conin@P3heb veracht:@J4an dat i@J3Godt den Heere,@M4er hoochst@93Maje@83yt@J4Heb moeten obedieren@G4In der gh@@3chticheyt.\n"
    .asciz
